# Generated by Django 3.1.4 on 2021-01-20 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
