# Generated by Django 3.1.4 on 2021-03-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_key_gen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license_key_gen',
            name='name',
            field=models.CharField(default='test name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='license_key_gen',
            name='license_key',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
